# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pokemon_pb2 as pokemon__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pokemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PokemonBattleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChoosePokemon = channel.unary_unary(
                '/pokemon.PokemonBattle/ChoosePokemon',
                request_serializer=pokemon__pb2.ChoosePokemonRequest.SerializeToString,
                response_deserializer=pokemon__pb2.ChoosePokemonResponse.FromString,
                _registered_method=True)
        self.Attack = channel.unary_unary(
                '/pokemon.PokemonBattle/Attack',
                request_serializer=pokemon__pb2.AttackRequest.SerializeToString,
                response_deserializer=pokemon__pb2.AttackResponse.FromString,
                _registered_method=True)
        self.GetBattleState = channel.unary_unary(
                '/pokemon.PokemonBattle/GetBattleState',
                request_serializer=pokemon__pb2.BattleStateRequest.SerializeToString,
                response_deserializer=pokemon__pb2.BattleStateResponse.FromString,
                _registered_method=True)


class PokemonBattleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChoosePokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Attack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBattleState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonBattleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChoosePokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.ChoosePokemon,
                    request_deserializer=pokemon__pb2.ChoosePokemonRequest.FromString,
                    response_serializer=pokemon__pb2.ChoosePokemonResponse.SerializeToString,
            ),
            'Attack': grpc.unary_unary_rpc_method_handler(
                    servicer.Attack,
                    request_deserializer=pokemon__pb2.AttackRequest.FromString,
                    response_serializer=pokemon__pb2.AttackResponse.SerializeToString,
            ),
            'GetBattleState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBattleState,
                    request_deserializer=pokemon__pb2.BattleStateRequest.FromString,
                    response_serializer=pokemon__pb2.BattleStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemon.PokemonBattle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pokemon.PokemonBattle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokemonBattle(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChoosePokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemon.PokemonBattle/ChoosePokemon',
            pokemon__pb2.ChoosePokemonRequest.SerializeToString,
            pokemon__pb2.ChoosePokemonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Attack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemon.PokemonBattle/Attack',
            pokemon__pb2.AttackRequest.SerializeToString,
            pokemon__pb2.AttackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBattleState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemon.PokemonBattle/GetBattleState',
            pokemon__pb2.BattleStateRequest.SerializeToString,
            pokemon__pb2.BattleStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
