# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pokemon.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pokemon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpokemon.proto\x12\x07pokemon\"?\n\x14\x43hoosePokemonRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x14\n\x0cpokemon_name\x18\x02 \x01(\t\"8\n\x15\x43hoosePokemonResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\rAttackRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0c\n\x04move\x18\x02 \x01(\t\".\n\x0e\x41ttackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04move\x18\x02 \x01(\t\"%\n\x12\x42\x61ttleStateRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"\x89\x01\n\x13\x42\x61ttleStateResponse\x12\x0f\n\x07player1\x18\x01 \x01(\t\x12\x0f\n\x07player2\x18\x02 \x01(\t\x12\'\n\x08pokemon1\x18\x03 \x01(\x0b\x32\x15.pokemon.PokemonState\x12\'\n\x08pokemon2\x18\x04 \x01(\x0b\x32\x15.pokemon.PokemonState\"7\n\x0cPokemonState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02hp\x18\x02 \x01(\x05\x12\r\n\x05moves\x18\x03 \x03(\t2\xe7\x01\n\rPokemonBattle\x12N\n\rChoosePokemon\x12\x1d.pokemon.ChoosePokemonRequest\x1a\x1e.pokemon.ChoosePokemonResponse\x12\x39\n\x06\x41ttack\x12\x16.pokemon.AttackRequest\x1a\x17.pokemon.AttackResponse\x12K\n\x0eGetBattleState\x12\x1b.pokemon.BattleStateRequest\x1a\x1c.pokemon.BattleStateResponseB\x14\xaa\x02\x11GrpcClient.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021GrpcClient.Protos'
  _globals['_CHOOSEPOKEMONREQUEST']._serialized_start=26
  _globals['_CHOOSEPOKEMONREQUEST']._serialized_end=89
  _globals['_CHOOSEPOKEMONRESPONSE']._serialized_start=91
  _globals['_CHOOSEPOKEMONRESPONSE']._serialized_end=147
  _globals['_ATTACKREQUEST']._serialized_start=149
  _globals['_ATTACKREQUEST']._serialized_end=197
  _globals['_ATTACKRESPONSE']._serialized_start=199
  _globals['_ATTACKRESPONSE']._serialized_end=245
  _globals['_BATTLESTATEREQUEST']._serialized_start=247
  _globals['_BATTLESTATEREQUEST']._serialized_end=284
  _globals['_BATTLESTATERESPONSE']._serialized_start=287
  _globals['_BATTLESTATERESPONSE']._serialized_end=424
  _globals['_POKEMONSTATE']._serialized_start=426
  _globals['_POKEMONSTATE']._serialized_end=481
  _globals['_POKEMONBATTLE']._serialized_start=484
  _globals['_POKEMONBATTLE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
